version: '2.4'
services:

  ldap1:
    image: osixia/openldap:1.5.0
    volumes:
      - ./user.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/user.ldif
    ports:
      - "3089:389"
    command: [ --copy-service, --loglevel, debug ]
    networks:
      ldap_network:
        aliases:
          - ldap.local

  ldap2:
    image: osixia/openldap:1.5.0
    volumes:
      - ./user.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/user.ldif
    ports:
      - "3099:389"
    command: [ --copy-service, --loglevel, debug ]
    networks:
      ldap_network:
        aliases:
          - ldap.local  

  es0:
    image: elasticsearch:9.3.0-SNAPSHOT
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - ./config:/usr/share/elasticsearch/config
    networks:
      - ldap_network

networks:
  ldap_network:
    driver: bridge