network.host: 0.0.0.0
cluster.name: docker-single-node-cluster
discovery.type: single-node
xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack:
  security:
    authc:
      realms:
        native:
          native1:
            order: 1
        ldap:
          ldap1:
            order: 2
            url: "ldap://ldap.local:389"
            bind_dn: "cn=admin,dc=example,dc=org"
            user_search:
              base_dn: "dc=example,dc=org"
              filter: "(cn={0})"
            group_search:
              base_dn: "dc=example,dc=org"
            load_balance:
              type: dns_failover
logger.org.elasticsearch.xpack.security.authc.ldap: "TRACE"
logger.com.unboundid.ldap.sdk: "DEBUG"

